package it.polimi.deib.provaFinale2014.controller;

/**
 * Enumerazione che elenca i comandi di controllo utili
 * nella comunicazione tra client e server
 */
public enum Command {
	AVAILABLE_ACTIONS,
	END,
	END_GAME,
	INSERT_COUPLE_REGION,
	INSERT_KILL_REGION,
	INSERT_ROAD,
	INSERT_STARTING_REGION,
	INSERT_CARD_TYPE,
	PLACE_SHEPHERD,
	SELL_CARD,
	SHEEPS_TO_KILL,
	SHEEPS_TO_MOVE,
	SOLD_CARDS,
	BOARD_STATE,
	END_BOARD_STATE,
	TURN_CHOICE,
	PERSONAL_INFO,
	END_PERSONAL_INFO,
	DISPLAY_MAP,
	DISPLAY_REGIONS_STATE,
	DISPLAY_BLACK_SHEEP_POSITION,
	DISPLAY_WOLF_POSITION,
	DISPLAY_ROADS_STATE,
	DISPLAY_BANKCARDS_STATE,
	DISPLAY_BANKFENCES_STATE,
	DISPLAY_PERSONAL_CARDS,
	DISPLAY_MONEY,
	BROADCAST,
	SHEPHERD_REWARDED,
	PING,
	CHOOSE_SHEPHERD,
	SHEPHERD_NUMBER, 
	WOLF_INFO,
	BLACKSHEEP_INFO, 
	EVOLVED_LAMBS, 
	TURN_OF_PLAYER,
	NICKNAMES,
	END_MARKET;
}
